routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/registeruser/get_profiles_by_type/{id}', 'RegisterUserController@getProfilesByType');

Route::resource('registeruser','RegisterUserController');

Route::resource('profile','UserProfileController');

Route::get('profile/get_profile_by_id/{id}', 'UserProfileController@getProfileById');

Route::resource('profile','UserProfileController');


// Start Change Password Routes

Route::get('/changePassword','HomeController@showChangePasswordForm');

Route::post('/changePassword','HomeController@changePassword')->name('changePassword');

// End Change Password Routes


// Start Cemetery Module Routes

Route::get('/cemeteries/get_states_by_country/{id}', 'CemeteryController@getStatesByCountry');

Route::get('/cemeteries/search_cemeteries', 'CemeteryController@searchCemeteries');

Route::post('/cemeteries/search_cemeteries', 'CemeteryController@searchCemeteries');

Route::resource('cemeteries','CemeteryController');

// End Cemetery Module Routes


// Start Item Module Routes

Route::get('/items/import_export_items_view', 'ItemController@importExportItemsView')->name('import.export.view');

Route::post('/items/import_items', 'ItemController@importItems')->name('import.items');

Route::post('/items/select_sheet', 'ItemController@selectSheetForImport')->name('select.sheet');

Route::post('/items/start_import_items', 'ItemController@startImportItems')->name('start.import.items');

Route::get('/items/export_items/{type}', 'ItemController@exportItems')->name('export.items');

Route::get('/items/search_items', 'ItemController@searchItems');

Route::post('/items/search_items', 'ItemController@searchItems');

Route::resource('items','ItemController');

// End Item Module Routes


// Start Special Offer Module Routes

Route::get('/special_offers/search_special_offers', 'SpecialOfferController@searchSpecialOffers');

Route::post('/special_offers/search_special_offers', 'SpecialOfferController@searchSpecialOffers');

Route::get('/special_offers/create_special_offer/{item}', ['uses' =>'SpecialOfferController@createSpecialOfferByItem'])->name('create_special_offer_by_item');

Route::post('/special_offers/store_special_offer/{item}', ['uses' =>'SpecialOfferController@storeSpecialOfferByItem'])->name('store_special_offer_by_item');

Route::get('/special_offers/edit_special_offer/{id}/{item}', ['uses' =>'SpecialOfferController@editSpecialOfferByItem'])->name('edit_special_offer_by_item');

Route::put('/special_offers/update_special_offer/{id}/{item}', ['uses' =>'SpecialOfferController@updateSpecialOfferByItem'])->name('update_special_offer_by_item');

Route::delete('/special_offers/destroy_special_offer/{id}/{item}', ['uses' =>'SpecialOfferController@destroySpecialOfferByItem'])->name('destroy_special_offer_by_item');

Route::resource('special_offers','SpecialOfferController');

// End Special Offer Module Routes


// Start Cemetery Item Module Routes

Route::get('/cemetery_items/import_export_loyalty_items_view', 'CemeteryItemController@importExportLoyaltyItemsView')->name('import.export.loyalty.items.view');

Route::post('/cemetery_items/import_loyalty_items', 'CemeteryItemController@importLoyaltyItems')->name('import.loyalty.items');

Route::post('/cemetery_items/select_sheet_loyalty_items', 'CemeteryItemController@selectSheetForLoyaltyItemsImport')->name('select.sheet.loyalty.items');

Route::post('/cemetery_items/start_import_loyalty_items', 'CemeteryItemController@startImportLoyaltyItems')->name('start.import.loyalty.items');

Route::get('/cemetery_items/export_items/{type}', 'CemeteryItemController@exportLoyaltyItems')->name('export.loyalty.items');

Route::get('/cemetery_items/search_cemetery_items', 'CemeteryItemController@searchCemeteryItems');

Route::post('/cemetery_items/search_cemetery_items', 'CemeteryItemController@searchCemeteryItems');

Route::get('/cemetery_items/create_cemetery_item/{item}', ['uses' =>'CemeteryItemController@createCemeteryItemByItem'])->name('create_cemetery_item_by_item');

Route::post('/cemetery_items/store_cemetery_item/{item}', ['uses' =>'CemeteryItemController@storeCemeteryItemByItem'])->name('store_cemetery_item_by_item');

Route::get('/cemetery_items/edit_cemetery_item/{id}/{item}', ['uses' =>'CemeteryItemController@editCemeteryItemByItem'])->name('edit_cemetery_item_by_item');

Route::put('/cemetery_items/update_cemetery_item/{id}/{item}', ['uses' =>'CemeteryItemController@updateCemeteryItemByItem'])->name('update_cemetery_item_by_item');

Route::delete('/cemetery_items/destroy_cemetery_item/{id}/{item}', ['uses' =>'CemeteryItemController@destroyCemeteryItemByItem'])->name('destroy_cemetery_item_by_item');

Route::resource('cemetery_items','CemeteryItemController');

// End Cemetery Item Module Routes


// Start Permission Module Routes

Route::get('permission/get_permission_by_id/{id}', 'UserPermissionController@getPermissionById');

Route::resource('permission','UserPermissionController');

// End Permission Module Routes


// Start Funeral Director Module Routes

Route::post('/funeral_directors/delete_loyalty_dollar_revaluation_request/{id}', 'FuneralDirectorController@deleteLoyaltyDollarRevaluationRequest')->name('delete.revaluation.request');

Route::post('/funeral_directors/update_loyalty_dollar_revaluation_request/{id}', 'FuneralDirectorController@updateLoyaltyDollarRevaluationRequest')->name('update.revaluation.request');

Route::get('/funeral_directors/loyalty_dollar_revaluation_requests', 'FuneralDirectorController@loyaltyDollarRevaluationRequests');

Route::post('/funeral_directors/create_loyalty_dollar_revaluation_request', 'FuneralDirectorController@createLoyaltyDollarRevaluationRequest')->name('create.revaluation.request');

Route::get('/funeral_directors/funeral_director_welcome_page', 'FuneralDirectorController@viewFuneralDirectorWelcomePage');

Route::post('/funeral_directors/approve_ld_transfer_request/{id}', 'FuneralDirectorController@approveLoyaltyDollarTransferRequest');

Route::post('/funeral_directors/reject_ld_transfer_request/{id}', 'FuneralDirectorController@rejectLoyaltyDollarTransferRequest');

Route::get('/funeral_directors/get_ld_balance_by_fd_id/{id}', 'FuneralDirectorController@getLdBalanceByFdId');

Route::get('/funeral_directors/search_loyalty_dollar_transfer_requests', 'FuneralDirectorController@searchLoyaltyDollarTransferRequests');

Route::post('/funeral_directors/search_loyalty_dollar_transfer_requests', 'FuneralDirectorController@searchLoyaltyDollarTransferRequests');

Route::get('/funeral_directors/search_funeral_directors', 'FuneralDirectorController@searchFuneralDirectors');

Route::post('/funeral_directors/search_funeral_directors', 'FuneralDirectorController@searchFuneralDirectors');

Route::post('/funeral_directors/set_loyalty_dollar_adjustment', 'FuneralDirectorController@setLoyaltyDollarAdjustment');

Route::post('/funeral_directors/create_loyalty_dollar_transfer_request', 'FuneralDirectorController@createLoyaltyDollarTransferRequest');

Route::resource('funeral_directors','FuneralDirectorController');

// End Funeral Director Module Routes


// Start Staff Module Routes

Route::get('/staff/staff_welcome_page', 'StaffController@viewStaffWelcomePage');

Route::get('/staff/get_loyalty_dollar_by_fd_id/{id}/{type}', 'StaffController@getLoyaltyDollarByFdId');

Route::get('/staff/get_points_by_cemetery_item/{id}/{type}/{cid}/{iid}', 'StaffController@getPointsByCemeteryItem');

Route::get('/staff/get_items_by_cemetery/{id}', 'StaffController@getItemsByCemetery');

// End Staff Module Routes


// Start Audit Module Routes

Route::get('/audits/search_audits', 'AuditController@searchAudits');

Route::post('/audits/search_audits', 'AuditController@searchAudits');

Route::resource('audits','AuditController')->only([
    'index', 'show'
]);

// End Audit Module Routes


// Start Point Report Module Routes

Route::get('/point_reports/point_reports_PDF/{fd}/{from}/{to}', ['uses' =>'PointReportController@generatePointReportsPDF'])->name('generate_point_reports_pdf');

Route::get('/point_reports/point_reports_fd/{id}', 'PointReportController@pointReportsFD')->name('view.point.reports.fd');

Route::get('/point_reports/view_point_reports_fd', 'PointReportController@viewPointReportsFD');

Route::post('/point_reports/view_point_reports_fd', 'PointReportController@viewPointReportsFD');

Route::get('/point_reports/view_point_reports', 'PointReportController@viewPointReports');

Route::post('/point_reports/view_point_reports', 'PointReportController@viewPointReports');

Route::resource('point_reports','PointReportController')->only([
    'index', 'show'
]);

// End Point Report Module Routes


// Start Configuration Module Routes

Route::resource('configurations','ConfigurationController')->only([
    'create', 'store'
]);

// End Configuration Module Routes


// Start Background Process Module Routes

Route::get('/background_process/view_error_details', 'BackgroundProcessController@viewErrorDetails')->name('view.error.details');

Route::post('/background_process/ignore_cms_trans_errors/{id}', 'BackgroundProcessController@ignoreCmsTransErrors')->name('ignore.cms.trans.errors');

Route::post('/background_process/unignore_cms_trans_errors/{id}', 'BackgroundProcessController@unignoreCmsTransErrors')->name('unignore.cms.trans.errors');

Route::get('/background_process/view_status_and_parameters', 'BackgroundProcessController@viewStatusParameters')->name('view.status.parameters');

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
//use Illuminate\Database\Eloquent\SoftDeletes;
use OwenIt\Auditing\Auditable;
use OwenIt\Auditing\Contracts\Auditable as AuditableContract;

class Item extends Model implements AuditableContract
{
    //use SoftDeletes;
    use Auditable;

    protected $table = 'items';

    protected $fillable = [
        'code',
        'description',
        'status',
        'gl_liability_code',
        'gl_cost_code'
    ];

    protected $dates = ['deleted_at'];

    public function cemeteryItems()
    {
        return $this->hasMany('App\CemeteryItem');
    }

    public function specialOffers()
    {
        return $this->hasMany('App\SpecialOffer');
    }
    
    /* public static function boot()
    {
        parent::boot();    
    
        static::deleted(function($item)
        {
            $item->cemeteryItems()->delete();
            $item->specialOffers()->delete();
        });
    }    */ 
}

resources/views/item/item-create.blade.php
@extends('layouts.master')

@section('title', 'Add Item')

@section('content')

    <!-- START JUMBOTRON -->
    <div class="jumbotron hide" data-pages="parallax">
        <div class=" container-fluid   container-fixed-lg sm-p-l-0 sm-p-r-0">
            <div class="inner">
                <!-- START BREADCRUMB -->
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('items.index') }}">Item</a></li>
                    <li class="breadcrumb-item active">Add Item</li>
                </ol>
                <!-- END BREADCRUMB -->
            </div>
        </div>
    </div>
    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class=" container-fluid   container-fixed-lg">
        <!-- BEGIN PlACE PAGE CONTENT HERE -->
        <div class="page-header padding-20-top">
            <div class="card-title"><a href="{{ route('items.index') }}" class="fa fa-angle-left go-back"></a> Add Item</div>
        </div>
        @if(\Session::has('success'))
            <div class="alert alert-success" id="success_msg" data-remove-delay="3000">
                <button class="close" data-dismiss="alert"></button>
                {{\Session::get('success')}}
            </div>
        @endif
        @if(\Session::has('error'))
            <div class="alert alert-danger" id="error_msg" data-remove-delay="3000">
                <button class="close" data-dismiss="alert"></button>
                {{\Session::get('error')}}
            </div>
        @endif
        <!-- START card -->
        <div class="row">
            <div class="col-md-12">
                <form method="POST" action="{{ route('items.store') }}" id="form-personal" role="form" autocomplete="off">
                    @csrf
                    <div class="card card-white card-shadow card-special">
                        <div class="card-block">
                            <div class="row clearfix">
                                <div class="col-md-4">
                                    <div class="form-group form-group-default required">
                                        <label>Item Code</label>
                                        <input type="text" class="form-control" value="{{ old('code') }}" id="code" placeholder="Item Code" name="code" required>
                                        @if ($errors->has('code'))
                                            <div class="error">{{ $errors->first('code') }}</div>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-8">
                                    <div class="form-group form-group-default required">
                                        <label>Item Description</label>
                                        <input type="text" class="form-control" value="{{ old('description') }}" id="description" placeholder="Item Description" name="description" required>
                                        @if ($errors->has('description'))
                                            <div class="error">{{ $errors->first('description') }}</div>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card card-white card-shadow card-special">
                        <div class="card-block">
                            <div class="row clearfix">
                                <div class="col-md-4">
                                    <div class="form-group form-group-default required">
                                        <label>Status</label>
                                        <div class="radio radio-success">
                                            <div class="row">
                                                <div class="col-md-3 radio-labels">
                                                    <input type="radio" value="1" name="status" id="active" checked="checked">
                                                    <label for="active">Active</label>
                                                </div>
                                                <div class="col-md-3 radio-labels">
                                                    <input type="radio" value="0" name="status" id="inactive">
                                                    <label for="inactive">Inactive</label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group form-group-default required">
                                        <label>GL Liability Code</label>
                                        <input type="text" class="form-control" value="{{ old('gl_liability_code') }}" id="gl_liability_code" placeholder="GL Liability Code" name="gl_liability_code" required>
                                        @if ($errors->has('gl_liability_code'))
                                            <div class="error">{{ $errors->first('gl_liability_code') }}</div>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group form-group-default required">
                                        <label>GL Cost Code</label>
                                        <input type="text" class="form-control" value="{{ old('gl_cost_code') }}" id="gl_cost_code" placeholder="GL Cost Code" name="gl_cost_code" required>
                                        @if ($errors->has('gl_cost_code'))
                                            <div class="error">{{ $errors->first('gl_cost_code') }}</div>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row clearfix padding-bottom-20">
                        <div class="col-md-6">
                            <a class="btn btn-light btn-lg" href="{{ route('items.index') }}">View all Items</a>
                        </div>
                        <div class="col-md-6 text-right">
                            @if(Session::get('create_item'))
                                <button class="btn btn-primary btn-lg" type="submit">Add Item</button>
                            @endif
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <!-- END card -->
        <!-- END PLACE PAGE CONTENT HERE -->
    </div>
    <!-- END CONTAINER FLUID -->

@endsection


@section('script')

@endsection

resources/views/item/item-search.blade.php
@extends('layouts.master')

@section('title', 'Items')

@section('content')

    <!-- START JUMBOTRON -->
    <div class="jumbotron hide" data-pages="parallax">
        <div class=" container-fluid   container-fixed-lg sm-p-l-0 sm-p-r-0">
            <div class="inner">
                <!-- START BREADCRUMB -->
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('items.index') }}">Item</a></li>
                    <li class="breadcrumb-item active">All Items</li>
                </ol>
                <!-- END BREADCRUMB -->
            </div>
        </div>
    </div>
    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class=" container-fluid   container-fixed-lg">
        <!-- BEGIN PlACE PAGE CONTENT HERE -->
        @if(\Session::has('success'))
            <div class="alert alert-success" id="success_msg" data-remove-delay="3000">
                <button class="close" data-dismiss="alert"></button>
                {{\Session::get('success')}}
            </div>
        @endif
        @if(\Session::has('error'))
            <div class="alert alert-danger" id="error_msg" data-remove-delay="3000">
                <button class="close" data-dismiss="alert"></button>
                {{\Session::get('error')}}
            </div>
        @endif
        <!-- START card -->
        <div class="page-header padding-20-top">
            <div class="card-title pull-left"><a href="{{ route('items.index') }}" class="fa fa-angle-left go-back"></a> All Items</div>
            <div class="pull-right">
                <form method="POST" action="{{ action('ItemController@searchItems') }}" id="form-personal" role="form" autocomplete="off">
                    @csrf
                    <div class="input-group">
                        <a class="btn btn-primary btn-rounded" style="margin-right: 30px;" href="{{ route('items.create') }}"><span class="fa fa-plus"></span>&nbsp;Add Item</a>
                        <input type="text" class="form-control form-search" name="search_value" value="{{ old('search_value') }}" placeholder="Search...">
                        <span class="input-group-btn">
                            <button class="btn btn-search btn-sm" type="submit"><span class="fa fa-search"></span></button>
                        </span>
                    </div>
                </form>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="card card-white card-shadow card-special">

            @if(count($items)==0)
                <div class="card-block text-center">No Results Available</div>
            @else

            <div class="card-block">
                <table class="table table-hover demo-table-search table-responsive-block">
                    <thead>
                    <tr>
                        <th>Code</th>
                        <th>Description</th>
                        <th>Special Offers</th>
                        <th>GL Liability Code</th>
                        <th>GL Cost Code</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>

                    @foreach($items as $item)

                        <tr class="gradeA">
                            <td>{{ $item->code }}</td>
                            <td>{{ $item->description }}</td>
                            <td>
                                @if($item->sp_count == 0)
                                    <span class="label label-danger">No</span>
                                @elseif($item->sp_count > 0)
                                    <span class="label label-info">Yes</span>
                                @else
                                    <span class="label bg-black">Undefined</span>
                                @endif
                            </td>
                            <td>{{ $item->gl_liability_code }}</td>
                            <td>{{ $item->gl_cost_code }}</td>
                            <td>
                                <form action="{{ route('items.destroy',$item->id) }}" method="POST" class="delete_record">

                                    @if(Session::get('read_item'))
                                        <a class="btn btn-xs btn-rounded btn-complete" href="{{ route('items.show',$item->id) }}"><span class="fa fa-eye"></span></a>
                                    @endif

                                    @if(Session::get('update_item'))
                                        <a class="btn btn-xs btn-rounded btn-success" href="{{ route('items.edit',$item->id) }}"><span class="fa fa-edit"></span></a>
                                    @endif

                                    @csrf
                                    @method('DELETE')

                                    @if(Session::get('delete_item'))
                                        <button type="submit" class="btn btn-xs btn-rounded btn-danger"><span class="fa fa-trash"></span></button>
                                    @endif

                                </form>
                            </td>
                        </tr>

                    @endforeach

                    </tbody>
                </table>
            </div>

            @endif

        </div>
        <!-- END card -->

        <div class="row pagination-div">
            <div class="col-md-12">
                <div class="pull-right">
                    {!! $items->links() !!}
                </div>
            </div>
        </div>

        <!-- END PLACE PAGE CONTENT HERE -->
    </div>
    <!-- END CONTAINER FLUID -->

@endsection


@section('script')

    <script>
        $(".delete_record").on("submit", function(){
            return confirm("Do you want to delete this record ?");
        });
    </script>

@endsection

resources/views/item/item-search2.blade.php
@extends('layouts.master')

@section('title', 'Items')

@section('content')

    <!-- START JUMBOTRON -->
    <div class="jumbotron hide" data-pages="parallax">
        <div class=" container-fluid   container-fixed-lg sm-p-l-0 sm-p-r-0">
            <div class="inner">
                <!-- START BREADCRUMB -->
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('items.index') }}">Item</a></li>
                    <li class="breadcrumb-item active">All Items</li>
                </ol>
                <!-- END BREADCRUMB -->
            </div>
        </div>
    </div>
    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class=" container-fluid   container-fixed-lg">
        <!-- BEGIN PlACE PAGE CONTENT HERE -->
        @if(\Session::has('success'))
            <div class="alert alert-success" id="success_msg" data-remove-delay="3000">
                <button class="close" data-dismiss="alert"></button>
                {{\Session::get('success')}}
            </div>
        @endif
        @if(\Session::has('error'))
            <div class="alert alert-danger" id="error_msg" data-remove-delay="3000">
                <button class="close" data-dismiss="alert"></button>
                {{\Session::get('error')}}
            </div>
        @endif
        <!-- START card -->
        <div class="page-header padding-20-top">
            <div class="card-title pull-left"><a href="{{ route('items.index') }}" class="fa fa-angle-left go-back"></a> Search Results @if($search_value!="")&nbsp;&nbsp;-&nbsp;&nbsp;<span style="font-size:14px;font-weight: bold;"> "{{ $search_value }}"</span> @endif </div>
            <a class="btn btn-warning btn-sm btn-rounded" style="margin-left: 30px;" href="{{ route('items.index') }}"><span class="fa fa-remove"></span>&nbsp;Clear</a>
                        
            <div class="pull-right">
                <form method="POST" action="{{ action('ItemController@searchItems') }}" id="form-personal" role="form" autocomplete="off">
                    @csrf
                    <div class="input-group">
                        <input type="text" class="form-control form-search" name="search_value" value="{{ old('search_value') }}" placeholder="Search...">
                        <span class="input-group-btn">
                            <button class="btn btn-search btn-sm" type="submit"><span class="fa fa-search"></span></button>
                        </span>
                    </div>
                </form>
            </div>
            
            <div class="clearfix"></div>
        </div>
        <div class="card card-white card-shadow card-special">

            @if(count($items)==0)
                <div class="card-block text-center">No Results Available</div>
            @else

            <div class="card-block">
                <table class="table table-hover demo-table-search table-responsive-block">
                    <thead>
                    <tr>
                        <th>Code</th>
                        <th>Description</th>
                        <th>GL Liability Code</th>
                        <th>GL Cost Code</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>

                    @foreach($items as $item)

                        <tr class="gradeA">
                            <td>{{ $item->code }}</td>
                            <td>{{ $item->description }}</td>
                            <td>{{ $item->gl_liability_code }}</td>
                            <td>{{ $item->gl_cost_code }}</td>
                            <td>
                                <form action="{{ route('items.destroy',$item->id) }}" method="POST" class="delete_record">

                                    @if(Session::get('read_item'))
                                        <a class="btn btn-xs btn-rounded btn-complete" href="{{ route('items.show',$item->id) }}"><span class="fa fa-eye"></span></a>
                                    @endif

                                    @if(Session::get('update_item'))
                                        <a class="btn btn-xs btn-rounded btn-success" href="{{ route('items.edit',$item->id) }}"><span class="fa fa-edit"></span></a>
                                    @endif

                                    @csrf
                                    @method('DELETE')

                                    @if(Session::get('delete_item'))
                                        <button type="submit" class="btn btn-xs btn-rounded btn-danger"><span class="fa fa-trash"></span></button>
                                    @endif

                                </form>
                            </td>
                        </tr>

                    @endforeach

                    </tbody>
                </table>
            </div>

            @endif

        </div>
        <!-- END card -->

        <div class="row pagination-div">
            <div class="col-md-12">
                <div class="pull-right">
                    {!! $items->links() !!}
                </div>
            </div>
        </div>

        <!-- END PLACE PAGE CONTENT HERE -->
    </div>
    <!-- END CONTAINER FLUID -->

@endsection


@section('script')

    <script>
        $(".delete_record").on("submit", function(){
            return confirm("Do you want to delete this record ?");
        });
    </script>

@endsection